name: Jest Tests

on:
  push:
    branches: [main, master]
    paths:
      - "src/**"
      - "__tests__/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/jest.yml"
      - "jest.config.js"
      - "tsconfig.json"
      - "next.config.mjs"
      - "prisma/**"

  pull_request:
    branches: [main, master]
    paths:
      - "src/**"
      - "__tests__/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/jest.yml"
      - "jest.config.js"
      - "tsconfig.json"
      - "next.config.mjs"
      - "prisma/**"

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_AWS_REGION: ${{ secrets.NEXT_PUBLIC_AWS_REGION }}
      NEXT_PUBLIC_AWS_ACCESS_KEY_ID: ${{ secrets.NEXT_PUBLIC_AWS_ACCESS_KEY_ID }}
      NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY: ${{ secrets.NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY }}
      NEXT_PUBLIC_SQS_QUEUE_URL: ${{ secrets.NEXT_PUBLIC_SQS_QUEUE_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}
      NEXT_PUBLIC_ROOT_URL: ${{ secrets.NEXT_PUBLIC_ROOT_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXT_PUBLIC_GA_ID: ${{ secrets.NEXT_PUBLIC_GA_ID }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      AUTH_DISCORD_ID: ${{ secrets.AUTH_DISCORD_ID }}
      AUTH_DISCORD_SECRET: ${{ secrets.AUTH_DISCORD_SECRET }}
      LINE_CLIENT_ID: ${{ secrets.LINE_CLIENT_ID }}
      LINE_CLIENT_SECRET: ${{ secrets.LINE_CLIENT_SECRET }}
      TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID }}
      TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}
      GITHUB_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GITHUB_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ secrets.NEXT_PUBLIC_GITHUB_CLIENT_SECRET }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      NEXT_PUBLIC_TEST_ENV: "test"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Run Jest tests
        run: npm test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: jest-report
          path: coverage/
          retention-days: 30
